[package]
name = "refx-pp-py"
version = "0.4.4"
edition = "2021"
authors = ["Max Ohn <ohn.m@hotmail.de>", "remeliah <anoletenu@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/refx-online/refx-pp-py"
description = "Difficulty and performance calculation for osu!"

[lib]
name = "refx_pp_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24", features = ["extension-module", "macros"] }
rosu-mods = { version = "0.3.0", default-features = false, features = ["serde"] }

refx-pp = { git = "https://github.com/refx-online/refx-pp-rs", rev = "834b22b0c4d03ebae6b142844ecdf74b3b277a43", features = ["sync"] }

serde = { version = "1.0.203" }

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
strip = true
